version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ./db/migration:/docker-entrypoint-initdb.d
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    
  server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file: .env
    environment:
      - DB_SOURCE=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      - db
