// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, name, password, profile_url
) VALUES (
  $1, $2, $3, $4
)
RETURNING user_id, username, name, password, profile_url, created_at
`

type CreateUserParams struct {
	Username   string         `json:"username"`
	Name       sql.NullString `json:"name"`
	Password   string         `json:"password"`
	ProfileUrl sql.NullString `json:"profile_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Name,
		arg.Password,
		arg.ProfileUrl,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Name,
		&i.Password,
		&i.ProfileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, name, password, profile_url, created_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Name,
		&i.Password,
		&i.ProfileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, name, password, profile_url, created_at FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Name,
		&i.Password,
		&i.ProfileUrl,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users 
SET username = COALESCE($2, username),
    name = COALESCE($3, name),
    password = COALESCE($4, password),
    profile_url = COALESCE($5, profile_url)
WHERE user_id = $1
RETURNING user_id, username, name, password, profile_url, created_at
`

type UpdateUserParams struct {
	UserID     int32          `json:"user_id"`
	Username   string         `json:"username"`
	Name       sql.NullString `json:"name"`
	Password   string         `json:"password"`
	ProfileUrl sql.NullString `json:"profile_url"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.Name,
		arg.Password,
		arg.ProfileUrl,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Name,
		&i.Password,
		&i.ProfileUrl,
		&i.CreatedAt,
	)
	return i, err
}
